# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.provider "virtualbox" do |vb|
     vb.cpus = 2
     vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    curl -fsSL get.docker.com | sh
    sudo usermod -aG docker vagrant
    # system:oracle@localhost:1521:xe
    docker run --name oracle --restart unless-stopped -p 1521:1521 -d wnameless/oracle-xe-11g
  SHELL
end
