# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 8080, host: 80 # Postgress
  config.vm.provider "virtualbox" do |vb|
     vb.cpus = 2
     vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    curl -fsSL get.docker.com | sh
    sudo usermod -aG docker vagrant
    docker run --name jenkins --restart unless-stopped -p 8080:8080 -p 50000:50000 -d jenkins/jenkins:lts
  SHELL
end
