# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 5432, host: 5432 # Postgress
  config.vm.network "forwarded_port", guest: 1521, host: 1521 # Oracle
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "4096"
  end
  #

  config.vm.provision "shell", inline: <<-SHELL
    curl -fsSL get.docker.com | sh
    sudo usermod -aG docker vagrant
    docker run --name postgres --restart unless-stopped -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres
  SHELL
end
